spring:
  application:
    name: corporate-user-service
  datasource:
    url: jdbc:h2:file:D://corporate-users
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    generate-ddl: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console

server:
  servlet:
    context-path: /corporate
  port: 8080

management:
  server:
    port: 9090
    base-path: "/"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled : false
  endpoints:
    web:
      exposure:
        include: '*'

  info :
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}


logging:
  level:
    root: info
    org.zalando.logbook: TRACE

    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
        #SQL=DEBUG:file:
    #name: var/logs/server.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    enabled: true
    path: /swagger-ui-custom.html
  #version: springdoc.version

api:
  version: 1.0-SNAPSHOT
  server:
    url: http://www.corporte.com
  description: The corporate API is used to create, update and delete users.


